language: clojure
env: OBB_SCENARIOS_TO_TEST=1000
notifications:
  slack: orionsbelt-game:QT4unoZGVBOvbSWiil1o1bm0
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
after_script:
  - bash -ex script/coveralls.sh
